name: Django CI/CD з Docker

on:
  push:
    branches: [ "main" ] # Запускати цей workflow при push у гілку main
  pull_request:
    branches: [ "main" ] # Запускати цей workflow при створенні або оновленні pull request в гілку main

jobs:
  build:
    runs-on: ubuntu-latest # Використовувати Ubuntu для виконання цього завдання
    steps:
    - uses: actions/checkout@v4 # Витягнути код репозиторію у віртуальне середовище

    - name: Налаштування Python 3.8
      uses: actions/setup-python@v5 # Встановити Python 3.8
      with:
        python-version: "3.8"

    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip # Оновити pip
        pip install -r requirements.txt # Встановити залежності Python з requirements.txt

    - name: Виконання міграцій
      run: python manage.py migrate # Виконати міграції Django для підготовки бази даних

    - name: Запуск тестів
      run: python manage.py test # Запустити тести Django

    - name: Збірка Docker-образу
      run: docker build -t ghcr.io/${{ github.repository }}:latest . # Зібрати Docker-образ з тегом ghcr.io/your-repo-name:latest

    - name: Вхід до GitHub Container Registry
      uses: docker/login-action@v3 # Увійти до GHCR
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }} # Використовувати ім'я власника репозиторію GitHub
        password: ${{ secrets.GITHUB_TOKEN }} # Використовувати автоматично згенерований токен GitHub

    - name: Завантаження Docker-образу до GHCR
      run: docker push ghcr.io/${{ github.repository }}:latest # Завантажити Docker-образ до GHCR
